// Standard Library includes
#include <iostream>
#include <string>

// For std::isalpha and std::isupper
#include <cctype>

// Our project headers
#include "TransformChar.hpp"

std::string tranformChar(const char in_char){
    /*
        take the input character and transform it according to the follwing:
        - Must be uppercase
        - Ignore alphanumeric characters
        - Chahnge number to English words, e.g. '0' -> "ZERO"
        char in_char: The character to transform
        return: The string generated by the transformed character
    */

    // Define output variable
    std::string out{""};
    
    // Uppercase alphabetic characters
    if (std::isalpha(in_char)) {
        out += std::toupper(in_char);
        return out;
    }

    // Transliterate digits to English word
    switch (in_char) {
        case '0':
            out += "ZERO";
            break;
        case '1':
            out += "ONE";
            break;
        case '2':
            out += "TWO";
            break;
        case '3':
            out += "THREE";
            break;
        case '4':
            out += "FOUR";
            break;
        case '5':
            out += "FIVE";
            break;
        case '6':
            out += "SIX";
            break;
        case '7':
            out += "SEVEN";
            break;
        case '8':
            out += "EIGHT";
            break;
        case '9':
            out += "NINE";
            break;
    }

    // If the character isn't alphabetic or numeric, DONT add it
    return out;
}

